# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /blog/:title/

# Setup
title:            Jonathan Reyes
tagline:          desarrollador de software
description:      ¡Hola! Soy un desarrollador de software de Quito, Ecuador. Trabajo actualmente en <a href="https://www.thoughtworks.com/es/">ThoughtWorks</a>.
url:              https://jreyes.org
baseurl:          /
paginate:         5

author:
  name:           Jonathan Reyes
  url:            https://jreyes.org

# Custom vars
version:          0.0.1

links:
  github:         https://github.com/jreyes33
  twitter:        https://twitter.com/jreyes33
  linkedin:       https://www.linkedin.com/in/jreyes33
