# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jonathan Reyes
tagline:          'Software Developer'
description:      'I am a Software Developer from Quito, Ecuador working for <a href="http://www.thoughtworks.com/">ThoughtWorks</a>'
url:              http://jreyes.org
baseurl:          '/'
paginate:         5

author:
  name:           'Jonathan Reyes'
  url:            http://jreyes.org

# Custom vars
version:          0.0.1

links:
  github:         https://github.com/jreyes33
  twitter:        https://twitter.com/jreyes33
  linkedin:       https://www.linkedin.com/in/jreyes33
