# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          ["jekyll-paginate"]

# Permalinks
permalink:        /blog/:title/

# Setup
title:            Jonathan Reyes
tagline:          desarrollador de software
description:      ¡Hola! Soy un desarrollador de software de Quito, Ecuador.
host:             0.0.0.0
url:              https://jreyes.org
baseurl:          /
paginate:         5

author:
  name:           Jonathan Reyes
  url:            https://jreyes.org

sass:
  sass_dir: _sass
  style: compressed

# Custom vars
version:          0.0.1

links:
  github:         https://github.com/jreyes33
  twitter:        https://twitter.com/jreyes33
  linkedin:       https://www.linkedin.com/in/jreyes33
