# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /blog/:title/

# Setup
title:            Jonathan Reyes
tagline:          Software Developer
description:      I am a Software Developer from Quito, Ecuador working for <a href="https://www.thoughtworks.com/">ThoughtWorks</a>
url:              https://jreyes.org
baseurl:          /
paginate:         5

author:
  name:           Jonathan Reyes
  url:            https://jreyes.org

# Custom vars
version:          0.0.1

links:
  github:         https://github.com/jreyes33
  twitter:        https://twitter.com/jreyes33
  linkedin:       https://www.linkedin.com/in/jreyes33
